{"uid":"a76753ec9b614a46","name":"Валидация: создание борды с именем — ожидаемый статус 400","fullName":"tests.test_backend.board.board_validation_test#test_create_board_name_validation","historyId":"0ed5e545d8c0f89bd81250283d88d1f1","time":{"start":1749799087822,"stop":1749799088368,"duration":546},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_verify_url","time":{"start":1749799082902,"stop":1749799082902,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"owner_client","time":{"start":1749799082902,"stop":1749799083439,"duration":537},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"pytestconfig","time":{"start":1749799082902,"stop":1749799082902,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"delete_output_dir","time":{"start":1749799082902,"stop":1749799082902,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"base_url","time":{"start":1749799082902,"stop":1749799082902,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"temp_space","time":{"start":1749799083440,"stop":1749799084269,"duration":829},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"temp_project","time":{"start":1749799084269,"stop":1749799085985,"duration":1716},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"passed","steps":[{"name":"Проверка, что API вернул статус 400 при number instead of string","time":{"start":1749799088367,"stop":1749799088368,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"attachments":[{"uid":"82b36b4a6257ae46","name":"stdout","source":"82b36b4a6257ae46.txt","type":"text/plain","size":91}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":1,"hasContent":true},"afterStages":[{"name":"temp_space::0","time":{"start":1749799117946,"stop":1749799118595,"duration":649},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"backend"},{"name":"parentSuite","value":"tests.test_backend.board"},{"name":"suite","value":"board_validation_test"},{"name":"host","value":"pkrvmxyh4eaekms"},{"name":"thread","value":"2539-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_backend.board.board_validation_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"expected_status","value":"400"},{"name":"name","value":"123"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":8,"skipped":0,"passed":7,"unknown":0,"total":15},"items":[{"uid":"1333a3ed6df19d4c","reportUrl":"https://vaizcom.github.io/autotests/129//#testresult/1333a3ed6df19d4c","status":"passed","time":{"start":1749798747802,"stop":1749798748086,"duration":284}},{"uid":"aa9cae355ff70c33","reportUrl":"https://vaizcom.github.io/autotests/128//#testresult/aa9cae355ff70c33","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f254b41e350>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749798175091,"stop":1749798175091,"duration":0}},{"uid":"f5270aefb9619b9e","reportUrl":"https://vaizcom.github.io/autotests/127//#testresult/f5270aefb9619b9e","status":"passed","time":{"start":1749797896324,"stop":1749797896845,"duration":521}},{"uid":"e1bdc2fda57b08a1","reportUrl":"https://vaizcom.github.io/autotests/126//#testresult/e1bdc2fda57b08a1","status":"passed","time":{"start":1749745006434,"stop":1749745006703,"duration":269}},{"uid":"1e836dbf62b97e33","reportUrl":"https://vaizcom.github.io/autotests/125//#testresult/1e836dbf62b97e33","status":"passed","time":{"start":1749744404256,"stop":1749744404563,"duration":307}},{"uid":"69680a16ed957b55","reportUrl":"https://vaizcom.github.io/autotests/124//#testresult/69680a16ed957b55","status":"passed","time":{"start":1749744318429,"stop":1749744318784,"duration":355}},{"uid":"2450583c99c27565","reportUrl":"https://vaizcom.github.io/autotests/123//#testresult/2450583c99c27565","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6ed7455e50>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749744002736,"stop":1749744002736,"duration":0}},{"uid":"4e1a34ca2e02a542","reportUrl":"https://vaizcom.github.io/autotests/122//#testresult/4e1a34ca2e02a542","status":"passed","time":{"start":1749743622795,"stop":1749743623159,"duration":364}},{"uid":"8c497ae3a02cb0c9","reportUrl":"https://vaizcom.github.io/autotests/119//#testresult/8c497ae3a02cb0c9","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc7b5913490>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742819883,"stop":1749742819883,"duration":0}},{"uid":"c02d0e2233dad1f0","reportUrl":"https://vaizcom.github.io/autotests/118//#testresult/c02d0e2233dad1f0","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9cb88f1f10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742667257,"stop":1749742667257,"duration":0}},{"uid":"6b102dfa1d2506a8","reportUrl":"https://vaizcom.github.io/autotests/117//#testresult/6b102dfa1d2506a8","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2b9f21f250>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742497013,"stop":1749742497013,"duration":0}},{"uid":"29ee04e0e3f2125c","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/29ee04e0e3f2125c","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233476,"stop":1749741233476,"duration":0}},{"uid":"b6c7dc4f6e84a0e1","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/b6c7dc4f6e84a0e1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740825946,"stop":1749740825946,"duration":0}},{"uid":"9450d640bb230b0","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/9450d640bb230b0","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740652720,"stop":1749740652720,"duration":0}}]},"tags":["backend"]},"source":"a76753ec9b614a46.json","parameterValues":["400","123"]}