{"uid":"6243f4d6530002d7","name":"Получение борды по boardId через /GetBoard","fullName":"tests.test_backend.board.test_board#test_get_board_by_id","historyId":"2b1c8a41ae9b94d897f68b7f410d75b0","time":{"start":1749744416663,"stop":1749744417292,"duration":629},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"delete_output_dir","time":{"start":1749744399429,"stop":1749744399429,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"_verify_url","time":{"start":1749744399429,"stop":1749744399429,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"pytestconfig","time":{"start":1749744399429,"stop":1749744399429,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"base_url","time":{"start":1749744399429,"stop":1749744399429,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"owner_client","time":{"start":1749744399429,"stop":1749744400163,"duration":734},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"temp_space","time":{"start":1749744400163,"stop":1749744401184,"duration":1021},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"temp_project","time":{"start":1749744401184,"stop":1749744402659,"duration":1475},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"passed","steps":[{"name":"Создание борды","time":{"start":1749744416663,"stop":1749744416973,"duration":310},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Получение борды по boardId через /GetBoard","time":{"start":1749744416973,"stop":1749744417292,"duration":319},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":2,"attachmentsCount":0,"hasContent":true},"afterStages":[{"name":"temp_space::0","time":{"start":1749744437355,"stop":1749744438003,"duration":648},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"backend"},{"name":"parentSuite","value":"tests.test_backend.board"},{"name":"suite","value":"test_board"},{"name":"host","value":"pkrvmxyh4eaekms"},{"name":"thread","value":"2515-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_backend.board.test_board"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":7,"skipped":0,"passed":3,"unknown":0,"total":10},"items":[{"uid":"85b3f3d58d0052f3","reportUrl":"https://vaizcom.github.io/autotests/124//#testresult/85b3f3d58d0052f3","status":"passed","time":{"start":1749744329174,"stop":1749744329732,"duration":558}},{"uid":"6b67dcd9aaa225af","reportUrl":"https://vaizcom.github.io/autotests/123//#testresult/6b67dcd9aaa225af","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6ed7455e50>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749744004827,"stop":1749744004827,"duration":0}},{"uid":"815224689dc48bc3","reportUrl":"https://vaizcom.github.io/autotests/122//#testresult/815224689dc48bc3","status":"passed","time":{"start":1749743632584,"stop":1749743633029,"duration":445}},{"uid":"529a2188903d37e1","reportUrl":"https://vaizcom.github.io/autotests/119//#testresult/529a2188903d37e1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc7b5913490>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742821916,"stop":1749742821916,"duration":0}},{"uid":"ddc64bf3ad652df7","reportUrl":"https://vaizcom.github.io/autotests/118//#testresult/ddc64bf3ad652df7","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9cb88f1f10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742669364,"stop":1749742669364,"duration":0}},{"uid":"46931e941ebe8213","reportUrl":"https://vaizcom.github.io/autotests/117//#testresult/46931e941ebe8213","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2b9f21f250>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742499166,"stop":1749742499166,"duration":0}},{"uid":"9c20e6c779b32015","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/9c20e6c779b32015","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235536,"stop":1749741235536,"duration":0}},{"uid":"6f5a171a399fe65","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/6f5a171a399fe65","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828126,"stop":1749740828126,"duration":0}},{"uid":"38262f66c5ea0c68","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/38262f66c5ea0c68","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654789,"stop":1749740654789,"duration":0}}]},"tags":["backend"]},"source":"6243f4d6530002d7.json","parameterValues":[]}