{"46c447386220279df8a67ddb0bb93498":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"c24ad3f07d5328d","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/c24ad3f07d5328d","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237181,"stop":1749741237181,"duration":0}},{"uid":"ae7455895d084bbf","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/ae7455895d084bbf","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829856,"stop":1749740829856,"duration":0}},{"uid":"199cfe5e8c638c39","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/199cfe5e8c638c39","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656459,"stop":1749740656459,"duration":0}}]},"ed19df0d673b3444776b6c72d0fc81fb":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"29492a69699344a6","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/29492a69699344a6","status":"passed","time":{"start":1749710092075,"stop":1749710092392,"duration":317}}]},"5a2ef8c4db5c6e746a7695fad89e5388":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"6c80f91408a340a8","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/6c80f91408a340a8","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235756,"stop":1749741235756,"duration":0}},{"uid":"1199f8e5eb00dcde","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/1199f8e5eb00dcde","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828355,"stop":1749740828355,"duration":0}},{"uid":"93be617d7a85471e","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/93be617d7a85471e","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655004,"stop":1749740655004,"duration":0}}]},"fd8cd4acc53d59b1fa966b43a96d2ad1":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"d291c45eab5b6e75","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/d291c45eab5b6e75","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235825,"stop":1749741235825,"duration":0}},{"uid":"f8e75f76d1d64540","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/f8e75f76d1d64540","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828427,"stop":1749740828427,"duration":0}},{"uid":"2599ba8231b157da","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/2599ba8231b157da","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655071,"stop":1749740655071,"duration":0}}]},"1398ce3b77213ef60e8e04fd29db073c":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"187a43f7efa7b3cd","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/187a43f7efa7b3cd","status":"passed","time":{"start":1749710076132,"stop":1749710076397,"duration":265}}]},"e8481dc54c2526a5fdf4fa6e36a52467":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"c6b467ed3cc1a6a7","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/c6b467ed3cc1a6a7","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236479,"stop":1749741236479,"duration":0}},{"uid":"23435ef04fd28e07","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/23435ef04fd28e07","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829111,"stop":1749740829111,"duration":0}},{"uid":"551975642c28aef","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/551975642c28aef","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655746,"stop":1749740655746,"duration":0}}]},"8c1f0eef4c5fc7bc16f4b3e7e1371366":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"b75d5dfe68a03fe1","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/b75d5dfe68a03fe1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235399,"stop":1749741235399,"duration":0}},{"uid":"5149976bd71cbf25","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/5149976bd71cbf25","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827982,"stop":1749740827982,"duration":0}},{"uid":"fb5e3b253eaa59cb","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/fb5e3b253eaa59cb","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654656,"stop":1749740654656,"duration":0}}]},"22465376a5a66c1166809a0212d01f3d":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"5fc2679cb010ea3f","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/5fc2679cb010ea3f","status":"passed","time":{"start":1749710077512,"stop":1749710077758,"duration":246}}]},"c03ab22bbfb7a0a46be6673b4f376e7e":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"470577b0952438c5","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/470577b0952438c5","status":"passed","time":{"start":1749710075617,"stop":1749710075845,"duration":228}}]},"99b0fd73ddae2b38f44f4ee7a6f343cf":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"5c0604c1ee71f426","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/5c0604c1ee71f426","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236114,"stop":1749741236114,"duration":0}},{"uid":"3c516882d1f853ea","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/3c516882d1f853ea","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828727,"stop":1749740828727,"duration":0}},{"uid":"3cb3e7b624a43e12","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/3cb3e7b624a43e12","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655361,"stop":1749740655361,"duration":0}}]},"3bb90e48424f59f8a34a20e9b0d230f7":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"d660da0b1f0a0dfa","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/d660da0b1f0a0dfa","status":"passed","time":{"start":1749710080240,"stop":1749710080506,"duration":266}}]},"93c9d10969f73a2fb8e9a5d94a0bd3e4":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"907827de9f0321ec","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/907827de9f0321ec","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741238036,"stop":1749741238036,"duration":0}},{"uid":"ee6dbf6a8e5a1a1d","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/ee6dbf6a8e5a1a1d","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740830759,"stop":1749740830759,"duration":0}},{"uid":"3cee901b4f7d417f","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/3cee901b4f7d417f","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740657312,"stop":1749740657312,"duration":0}}]},"d649105f2ff3b1ae2e81c378d2effa89":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"56aa499f89c996cb","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/56aa499f89c996cb","status":"passed","time":{"start":1749710088369,"stop":1749710088630,"duration":261}}]},"6a3c1b83f002b7802a7a6b30a5524b6d":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"6673d0538380ea73","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/6673d0538380ea73","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236762,"stop":1749741236762,"duration":0}},{"uid":"f4feb20712b8f71b","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/f4feb20712b8f71b","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829414,"stop":1749740829414,"duration":0}},{"uid":"7145387e870e5470","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/7145387e870e5470","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656035,"stop":1749740656035,"duration":0}}]},"864fdeb85c223952a21373ac5c6abb0e":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"209d088b6ed741dd","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/209d088b6ed741dd","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235978,"stop":1749741235978,"duration":0}},{"uid":"566b54cc510fd951","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/566b54cc510fd951","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828583,"stop":1749740828583,"duration":0}},{"uid":"1078b358566939fb","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/1078b358566939fb","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655222,"stop":1749740655222,"duration":0}}]},"ac963095d3bc3ce572ac573fbbeb0033":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"b80d7024e8228af1","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/b80d7024e8228af1","status":"passed","statusDetails":"XPASS Пограничное значение 0 требует уточнения требований","time":{"start":1749710076717,"stop":1749710076979,"duration":262}}]},"99478b044499ecd5ffab9799dbe0f2af":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"3ce0a9e6e424eeba","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/3ce0a9e6e424eeba","status":"passed","time":{"start":1749710090404,"stop":1749710091009,"duration":605}}]},"7ad82ce3573c927f8f61849c703158ad":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"25a4d9a6344a9716","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/25a4d9a6344a9716","status":"passed","time":{"start":1749710067433,"stop":1749710068588,"duration":1155}}]},"f5fcba2954dea28a02a2d0d76c93a574":{"statistic":{"failed":0,"broken":0,"skipped":3,"passed":0,"unknown":0,"total":3},"items":[{"uid":"771b2e4e5863314d","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/771b2e4e5863314d","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234893,"stop":1749741234893,"duration":0}},{"uid":"1f53b665b1d08f96","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/1f53b665b1d08f96","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827453,"stop":1749740827453,"duration":0}},{"uid":"5ca8e8b5cef49e23","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/5ca8e8b5cef49e23","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654156,"stop":1749740654156,"duration":0}}]},"705defd21aa9ab40e3a53abd3f4a692e":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"e3632fe5ff1ae63b","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/e3632fe5ff1ae63b","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233969,"stop":1749741233969,"duration":0}},{"uid":"ec1787c1bb6b84f0","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/ec1787c1bb6b84f0","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826478,"stop":1749740826478,"duration":0}},{"uid":"402791abf7e5552d","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/402791abf7e5552d","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653231,"stop":1749740653231,"duration":0}}]},"338a8c76757e5dbf6a99937f3a0b9c6c":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"7fa2887e17df3d51","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/7fa2887e17df3d51","status":"passed","time":{"start":1749710064420,"stop":1749710065107,"duration":687}}]},"0ea50b549e0df50f7bdb11e41aaa2c55":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"86b4882683483236","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/86b4882683483236","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237548,"stop":1749741237548,"duration":0}},{"uid":"dfe50b07a78b0258","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/dfe50b07a78b0258","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740830242,"stop":1749740830242,"duration":0}},{"uid":"a1c58f783585574a","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/a1c58f783585574a","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656824,"stop":1749740656824,"duration":0}}]},"efd7138539abc04c8aaf764199111ca9":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"88687688fcc295c4","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/88687688fcc295c4","status":"passed","time":{"start":1749710080785,"stop":1749710081050,"duration":265}}]},"7cb92359528795ff2f3fc367cc98d702":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"2239628adc5ba231","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/2239628adc5ba231","status":"passed","time":{"start":1749710065415,"stop":1749710065623,"duration":208}}]},"f6156a906b129d629f76e0c394440ef1":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"e614b0933b677d5c","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/e614b0933b677d5c","status":"passed","time":{"start":1749710075149,"stop":1749710075375,"duration":226}}]},"5205f1b9cdf79b433aabe9276c531fef":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"a40c60dd7382f28b","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/a40c60dd7382f28b","status":"passed","statusDetails":"XPASS Нет валидации на превышение лимита","time":{"start":1749710077245,"stop":1749710077510,"duration":265}}]},"588db8b288c27e6a711fbc0c4d255ce7":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"1b7a4ba652c48f5e","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/1b7a4ba652c48f5e","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236829,"stop":1749741236829,"duration":0}},{"uid":"5722a1fedb9ecdaf","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/5722a1fedb9ecdaf","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829486,"stop":1749740829486,"duration":0}},{"uid":"f42cfa79463e631d","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/f42cfa79463e631d","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656102,"stop":1749740656102,"duration":0}}]},"d02ef43a2bc9ab8d59ee11eed9b667f7":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"1754820ca7f2855b","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/1754820ca7f2855b","status":"passed","statusDetails":"XPASS Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)","time":{"start":1749710079033,"stop":1749710079240,"duration":207}}]},"74fc1fc8b34508057004265b516f98d8":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"ad94987fc7ee55b2","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/ad94987fc7ee55b2","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233332,"stop":1749741233332,"duration":0}},{"uid":"39f5fa0eed1397b4","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/39f5fa0eed1397b4","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740825792,"stop":1749740825792,"duration":0}},{"uid":"9a607d62ddb92e94","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/9a607d62ddb92e94","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740652571,"stop":1749740652571,"duration":0}}]},"069e5b0ffd6f19d3e03545a79e6611ab":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"85c76bdd38944178","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/85c76bdd38944178","status":"passed","time":{"start":1749710081051,"stop":1749710081342,"duration":291}}]},"acacc68f9aa9d69379721008cc6eb26c":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"9d4a4c8210e95b45","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/9d4a4c8210e95b45","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233756,"stop":1749741233756,"duration":0}},{"uid":"d8bc5b3009bea590","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/d8bc5b3009bea590","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826252,"stop":1749740826252,"duration":0}},{"uid":"1b7840338f074cc4","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/1b7840338f074cc4","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653011,"stop":1749740653011,"duration":0}}]},"bfa58120a74e7ec91178e3d07c464ca6":{"statistic":{"failed":0,"broken":0,"skipped":3,"passed":0,"unknown":0,"total":3},"items":[{"uid":"367e5e062e72fa72","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/367e5e062e72fa72","status":"skipped","statusDetails":"XFAIL Бэк не валидирует тип limit — строка вместо числа\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234604,"stop":1749741234604,"duration":0}},{"uid":"64cbeceeda807680","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/64cbeceeda807680","status":"skipped","statusDetails":"XFAIL Бэк не валидирует тип limit — строка вместо числа\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827152,"stop":1749740827152,"duration":0}},{"uid":"f5f2d0e1cbf3556b","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/f5f2d0e1cbf3556b","status":"skipped","statusDetails":"XFAIL Бэк не валидирует тип limit — строка вместо числа\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653870,"stop":1749740653870,"duration":0}}]},"d2b270eae677fc65d8efb9fab4ba78db":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"788c1c4116b09a12","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/788c1c4116b09a12","status":"passed","time":{"start":1749710074721,"stop":1749710074928,"duration":207}}]},"0442f9c7d224bc8687eaed2e1cb49113":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"7e92754c1de8096e","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/7e92754c1de8096e","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233610,"stop":1749741233610,"duration":0}},{"uid":"cba9a428d01bdad4","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/cba9a428d01bdad4","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826089,"stop":1749740826089,"duration":0}},{"uid":"7fe755f44568e578","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/7fe755f44568e578","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740652858,"stop":1749740652858,"duration":0}}]},"f710223ac1667f411f9a1cb69aac60b6":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"f0feee3bd7d5bd50","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/f0feee3bd7d5bd50","status":"passed","time":{"start":1749710063667,"stop":1749710064419,"duration":752}}]},"08593dd22619fad55901b674093e1d22":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"f000e8330adbc554","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/f000e8330adbc554","status":"passed","time":{"start":1749710074930,"stop":1749710075147,"duration":217}}]},"9d6a03bb91a595c98d003269b6d83212":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"797d7724f6b0a015","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/797d7724f6b0a015","status":"passed","time":{"start":1749710074361,"stop":1749710074719,"duration":358}}]},"99a4052fdbfecf9a17975ca9a31b5b86":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"d098b7e2dabfb8a1","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/d098b7e2dabfb8a1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237044,"stop":1749741237044,"duration":0}},{"uid":"2d9c7e8a4b4d754d","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/2d9c7e8a4b4d754d","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829712,"stop":1749740829712,"duration":0}},{"uid":"76a096653d2a1918","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/76a096653d2a1918","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656324,"stop":1749740656324,"duration":0}}]},"c6ccc02a8c0f219518652dfc2869691f":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"85c7000c6d494a7f","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/85c7000c6d494a7f","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237329,"stop":1749741237329,"duration":0}},{"uid":"8dab539b914c1ce3","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/8dab539b914c1ce3","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740830012,"stop":1749740830012,"duration":0}},{"uid":"ea24d786cbce66d1","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/ea24d786cbce66d1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656607,"stop":1749740656607,"duration":0}}]},"d37f83e88e93d8e03e9e37a101bfefcb":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"87fc009e9595b8f7","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/87fc009e9595b8f7","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234036,"stop":1749741234036,"duration":0}},{"uid":"fb6e96a8af23ad11","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/fb6e96a8af23ad11","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826551,"stop":1749740826551,"duration":0}},{"uid":"b142f4dbc6ed39b4","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/b142f4dbc6ed39b4","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653299,"stop":1749740653299,"duration":0}}]},"2f13c1eb27b43c336890b025a8f1b4de":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"75450c6419f80029","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/75450c6419f80029","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233823,"stop":1749741233823,"duration":0}},{"uid":"887047b409043ed9","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/887047b409043ed9","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826324,"stop":1749740826324,"duration":0}},{"uid":"f4cf3a4107e7b8ae","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/f4cf3a4107e7b8ae","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653083,"stop":1749740653083,"duration":0}}]},"82160e7772af33bbbe5fd015a19df11b":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"4a57533d2b4bcb38","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/4a57533d2b4bcb38","status":"passed","statusDetails":"XPASS Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)","time":{"start":1749710078836,"stop":1749710079031,"duration":195}}]},"cd7dba37b3580c67a4ebb74b88610734":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"f16f102d69acec0f","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/f16f102d69acec0f","status":"passed","time":{"start":1749710075377,"stop":1749710075615,"duration":238}}]},"b70f00b11f2f6d71a461f9e743b520ea":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"143a2e33bb7d027b","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/143a2e33bb7d027b","status":"passed","time":{"start":1749710087582,"stop":1749710087777,"duration":195}}]},"3a95a2f13d3f56e5a1a48895483f8e88":{"statistic":{"failed":0,"broken":0,"skipped":3,"passed":0,"unknown":0,"total":3},"items":[{"uid":"f34daf0668096fc4","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/f34daf0668096fc4","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235041,"stop":1749741235041,"duration":0}},{"uid":"f72576a70fe6cd39","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/f72576a70fe6cd39","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827609,"stop":1749740827609,"duration":0}},{"uid":"cf71936d2d2b3fe2","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/cf71936d2d2b3fe2","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654302,"stop":1749740654302,"duration":0}}]},"ebff4d421c42dae81152272707dbe212":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"7abf065350aa2b1b","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/7abf065350aa2b1b","status":"passed","time":{"start":1749710065837,"stop":1749710066061,"duration":224}}]},"77ae0ed397b8c98fbd9ab45add82f64d":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"32dc9f6fa2a04bdc","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/32dc9f6fa2a04bdc","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237113,"stop":1749741237113,"duration":0}},{"uid":"6b12480a19adc20a","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/6b12480a19adc20a","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829784,"stop":1749740829784,"duration":0}},{"uid":"b33e51f5bdc3a29b","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/b33e51f5bdc3a29b","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656391,"stop":1749740656391,"duration":0}}]},"d6a9969c82f00983f302eed25739e544":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"52d155a65a6e5be9","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/52d155a65a6e5be9","status":"passed","time":{"start":1749710073452,"stop":1749710074359,"duration":907}}]},"d8718b249151510a31bb6c8cf801eeec":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"dff0511dcb761cf8","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/dff0511dcb761cf8","status":"passed","time":{"start":1749710066528,"stop":1749710066843,"duration":315}}]},"547dbefe405d5fa0da59c6458ce10487":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"110011bcd7a89e0a","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/110011bcd7a89e0a","status":"passed","time":{"start":1749710085460,"stop":1749710087083,"duration":1623}}]},"217527e672a6bfb3593814b4f4cb78f3":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"472e4738d8db695c","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/472e4738d8db695c","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235618,"stop":1749741235618,"duration":0}},{"uid":"91418692aca41f04","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/91418692aca41f04","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828212,"stop":1749740828212,"duration":0}},{"uid":"7a295802f552ae12","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/7a295802f552ae12","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654870,"stop":1749740654870,"duration":0}}]},"acc812294776661969211b504a77d787":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"a5c90a5d6fac4542","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/a5c90a5d6fac4542","status":"passed","time":{"start":1749710082807,"stop":1749710083351,"duration":544}}]},"4d84a36cf568cde9b56bcd74fcb17bfb":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"6406fdc149a40adf","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/6406fdc149a40adf","status":"passed","time":{"start":1749710079953,"stop":1749710080238,"duration":285}}]},"4bf705b401f5a46d831f420f10642a75":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"c4a144cedd7bf906","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/c4a144cedd7bf906","status":"passed","time":{"start":1749710065625,"stop":1749710065835,"duration":210}}]},"86261103e1821ad85693584e7e543758":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"6a5fcc47ddd7f87d","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/6a5fcc47ddd7f87d","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237750,"stop":1749741237750,"duration":0}},{"uid":"28dbd09bf23c7342","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/28dbd09bf23c7342","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740830458,"stop":1749740830458,"duration":0}},{"uid":"790a9600e7d39f97","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/790a9600e7d39f97","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740657025,"stop":1749740657025,"duration":0}}]},"0b2a7d1bed4c27399b5223a7f09400df":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"a9b130e73572a291","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/a9b130e73572a291","status":"passed","statusDetails":"XPASS Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)","time":{"start":1749710078440,"stop":1749710078632,"duration":192}}]},"9baa6e492cdfdac9cb939f1743051e72":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"4a73c388d07e94bf","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/4a73c388d07e94bf","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235686,"stop":1749741235686,"duration":0}},{"uid":"7e5efcd54ea4903f","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/7e5efcd54ea4903f","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828283,"stop":1749740828283,"duration":0}},{"uid":"68e581d5d6337925","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/68e581d5d6337925","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654937,"stop":1749740654937,"duration":0}}]},"ff32a1e690c990c801cfb3687f1d7053":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"f2ece72fd7c6f71b","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/f2ece72fd7c6f71b","status":"passed","time":{"start":1749710083352,"stop":1749710083872,"duration":520}}]},"3a25dc7653bc876f8241f8e8601c86dd":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"10cd7b3934b35f76","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/10cd7b3934b35f76","status":"passed","time":{"start":1749710070159,"stop":1749710071133,"duration":974}}]},"c08f72ed6aebf577da9883ad782e93ae":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"2c995ea3e6024d12","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/2c995ea3e6024d12","status":"passed","time":{"start":1749710091011,"stop":1749710091454,"duration":443}}]},"f62c40c0ae82d83b4ce8e3b76c708c13":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"9dfb7005b2867689","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/9dfb7005b2867689","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236331,"stop":1749741236331,"duration":0}},{"uid":"b48afe4d955a4836","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/b48afe4d955a4836","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828955,"stop":1749740828955,"duration":0}},{"uid":"db403c3f1bf0134f","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/db403c3f1bf0134f","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655597,"stop":1749740655597,"duration":0}}]},"e590b902bb04a2241c8a3ba5ffb8b269":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"ace83131ee06683f","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/ace83131ee06683f","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237683,"stop":1749741237683,"duration":0}},{"uid":"f1d988af61b621d1","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/f1d988af61b621d1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740830386,"stop":1749740830386,"duration":0}},{"uid":"d2cdb7b521cefae2","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/d2cdb7b521cefae2","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656958,"stop":1749740656958,"duration":0}}]},"68a947e89b785f6e204395ece80e9f1c":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"2c1090fc37e6f410","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/2c1090fc37e6f410","status":"passed","time":{"start":1749710080508,"stop":1749710080783,"duration":275}}]},"5f045bcc387ecdf0477bfd0667e2b715":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"c830b6ac3fe1949","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/c830b6ac3fe1949","status":"passed","time":{"start":1749710083874,"stop":1749710084407,"duration":533}}]},"013c6e237261f2ed236ec6dbe151456e":{"statistic":{"failed":0,"broken":0,"skipped":3,"passed":0,"unknown":0,"total":3},"items":[{"uid":"5416ca002be67173","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/5416ca002be67173","status":"skipped","statusDetails":"XFAIL Нет валидации на превышение лимита\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234470,"stop":1749741234470,"duration":0}},{"uid":"52f8c74f9a91ca32","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/52f8c74f9a91ca32","status":"skipped","statusDetails":"XFAIL Нет валидации на превышение лимита\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827009,"stop":1749740827009,"duration":0}},{"uid":"2b74647dad0fff3b","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/2b74647dad0fff3b","status":"skipped","statusDetails":"XFAIL Нет валидации на превышение лимита\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653736,"stop":1749740653736,"duration":0}}]},"0cd3d57e91fa3a37bb7da66c8c68baae":{"statistic":{"failed":0,"broken":0,"skipped":3,"passed":0,"unknown":0,"total":3},"items":[{"uid":"dc543c8663f7451d","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/dc543c8663f7451d","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234960,"stop":1749741234960,"duration":0}},{"uid":"87f5eb112ce870f4","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/87f5eb112ce870f4","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827524,"stop":1749740827524,"duration":0}},{"uid":"493806ea40ae8f0","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/493806ea40ae8f0","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654222,"stop":1749740654222,"duration":0}}]},"79e825556c8e979fb839ef559890d9cb":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"de51bbe4cd46760e","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/de51bbe4cd46760e","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233265,"stop":1749741233265,"duration":0}},{"uid":"ce81737bf595c70f","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/ce81737bf595c70f","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740825720,"stop":1749740825720,"duration":0}},{"uid":"8175a3373a3849e8","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/8175a3373a3849e8","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740652501,"stop":1749740652501,"duration":0}}]},"c74eaa863893cad4aae07c879a87b297":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"11b2dc6fdf1a3969","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/11b2dc6fdf1a3969","status":"passed","time":{"start":1749710072483,"stop":1749710073450,"duration":967}}]},"16c764d63f1b5b805cfdf995f3c35104":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"10983c1bbff32251","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/10983c1bbff32251","status":"passed","time":{"start":1749710084409,"stop":1749710084926,"duration":517}}]},"2cb76e81e4a27f4607f4f034fc6f46c4":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"154c15b19e87ecdd","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/154c15b19e87ecdd","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236963,"stop":1749741236963,"duration":0}},{"uid":"d94b9fa3ce10a238","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/d94b9fa3ce10a238","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829629,"stop":1749740829629,"duration":0}},{"uid":"d562fa9874c2de3e","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/d562fa9874c2de3e","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656241,"stop":1749740656241,"duration":0}}]},"8e009e32941269cff89af11bf8a2d343":{"statistic":{"failed":0,"broken":0,"skipped":3,"passed":0,"unknown":0,"total":3},"items":[{"uid":"38f0e7612447b5d0","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/38f0e7612447b5d0","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234825,"stop":1749741234825,"duration":0}},{"uid":"89502121a1a986c5","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/89502121a1a986c5","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827380,"stop":1749740827380,"duration":0}},{"uid":"3632341558f8cbd7","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/3632341558f8cbd7","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654090,"stop":1749740654090,"duration":0}}]},"390d391510dbcb2ca791616745e65dfc":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"60eb5bf5a48c41c1","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/60eb5bf5a48c41c1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234537,"stop":1749741234537,"duration":0}},{"uid":"676ecffccf86db94","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/676ecffccf86db94","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827080,"stop":1749740827080,"duration":0}},{"uid":"dfbc62a13c8834e9","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/dfbc62a13c8834e9","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653803,"stop":1749740653803,"duration":0}}]},"fb497443fece2a3ff628735376d0f59b":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"220505766cd3be5b","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/220505766cd3be5b","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237247,"stop":1749741237247,"duration":0}},{"uid":"7fb68d6b5bfe9579","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/7fb68d6b5bfe9579","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829928,"stop":1749740829928,"duration":0}},{"uid":"328b753a9e88a851","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/328b753a9e88a851","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656525,"stop":1749740656525,"duration":0}}]},"d79246ecdcba044c4ab558d6842e18d8":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"7c7f6a3e5e6bfa7b","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/7c7f6a3e5e6bfa7b","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236263,"stop":1749741236263,"duration":0}},{"uid":"68e73c55bb0ca0e4","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/68e73c55bb0ca0e4","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828883,"stop":1749740828883,"duration":0}},{"uid":"baab98889b9d837","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/baab98889b9d837","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655527,"stop":1749740655527,"duration":0}}]},"cb26046c5217fbeb537f161dd0d69c42":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"77083a0227e9f491","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/77083a0227e9f491","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236398,"stop":1749741236398,"duration":0}},{"uid":"bc25962f275a3253","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/bc25962f275a3253","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829027,"stop":1749740829027,"duration":0}},{"uid":"4a50e6fdd361ab72","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/4a50e6fdd361ab72","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655665,"stop":1749740655665,"duration":0}}]},"251a80ad814570f85a9af75f2713c285":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"24a56f92db6de8a1","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/24a56f92db6de8a1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236681,"stop":1749741236681,"duration":0}},{"uid":"d2630b966f4830de","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/d2630b966f4830de","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829327,"stop":1749740829327,"duration":0}},{"uid":"3c5ecb704380477","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/3c5ecb704380477","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655950,"stop":1749740655950,"duration":0}}]},"26194cff7401f257c849131c9ca01f16":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"148e0e22b9c724c5","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/148e0e22b9c724c5","status":"passed","time":{"start":1749710089409,"stop":1749710089781,"duration":372}}]},"4cdfa43c32bf09a0f7ffad79899ee8a4":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"77da922abbdba463","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/77da922abbdba463","status":"passed","statusDetails":"XPASS Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)","time":{"start":1749710078241,"stop":1749710078439,"duration":198}}]},"faa5dde8e7f920bda1d8a3851ce59ecc":{"statistic":{"failed":0,"broken":0,"skipped":3,"passed":0,"unknown":0,"total":3},"items":[{"uid":"4602119c8863811d","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/4602119c8863811d","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235109,"stop":1749741235109,"duration":0}},{"uid":"c987c22146dacb1b","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/c987c22146dacb1b","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827681,"stop":1749740827681,"duration":0}},{"uid":"823e114efaf2ad8","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/823e114efaf2ad8","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654369,"stop":1749740654369,"duration":0}}]},"6c5b427d61fe4d666ba62ecf81baae11":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"41e321d0a3bcb500","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/41e321d0a3bcb500","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235178,"stop":1749741235178,"duration":0}},{"uid":"b2c1882c477c678c","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/b2c1882c477c678c","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827753,"stop":1749740827753,"duration":0}},{"uid":"e92a42ba66ba298f","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/e92a42ba66ba298f","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654437,"stop":1749740654437,"duration":0}}]},"39196e6a9423ffd3a5f4eed4e8f48fe7":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"6c459975cdb20499","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/6c459975cdb20499","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237464,"stop":1749741237464,"duration":0}},{"uid":"298fdd06df377db1","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/298fdd06df377db1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740830156,"stop":1749740830156,"duration":0}},{"uid":"aae3412f41b0b78c","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/aae3412f41b0b78c","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656741,"stop":1749740656741,"duration":0}}]},"8eb4ab24b80f6134451e02d56ad4651a":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"f592e5cb740c04b0","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/f592e5cb740c04b0","status":"passed","time":{"start":1749710089782,"stop":1749710090143,"duration":361}}]},"3e1563743b66960e98eb5d040ad45755":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"2968022726cc18cb","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/2968022726cc18cb","status":"passed","statusDetails":"XPASS Бэк не валидирует тип limit — строка вместо числа","time":{"start":1749710077759,"stop":1749710078002,"duration":243}}]},"afc5fc111fa94b83f0d65cdbb5fd27f8":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"3e819f9fcf5ac4b3","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/3e819f9fcf5ac4b3","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236896,"stop":1749741236896,"duration":0}},{"uid":"be6cb9856a280fb","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/be6cb9856a280fb","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829557,"stop":1749740829557,"duration":0}},{"uid":"89c2a00c5d7b4246","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/89c2a00c5d7b4246","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656169,"stop":1749740656169,"duration":0}}]},"d8a6ada6c0c23e8fac1a18846be41a49":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"de21a34d7656bd49","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/de21a34d7656bd49","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234389,"stop":1749741234389,"duration":0}},{"uid":"d088e36fbe946009","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/d088e36fbe946009","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826923,"stop":1749740826923,"duration":0}},{"uid":"7415f2815505c2d1","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/7415f2815505c2d1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653653,"stop":1749740653653,"duration":0}}]},"d2994232afaebbca4bcee199d13d7a07":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"e91e091596853f5e","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/e91e091596853f5e","status":"passed","statusDetails":"XPASS Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)","time":{"start":1749710078634,"stop":1749710078835,"duration":201}}]},"5ea62342824883d5d2411e3514f95d41":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"f929da4342291d99","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/f929da4342291d99","status":"passed","time":{"start":1749710071938,"stop":1749710072481,"duration":543}}]},"58d2e040e062b49dbdcdd1cdc411c7df":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"dfb34cb0cea73d66","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/dfb34cb0cea73d66","status":"passed","time":{"start":1749710067090,"stop":1749710067431,"duration":341}}]},"171b02b7dd153b401399265949d9a8aa":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"32a2608a81999163","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/32a2608a81999163","status":"passed","statusDetails":"XPASS Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)","time":{"start":1749710079242,"stop":1749710079719,"duration":477}}]},"7c9aa540eca22d9f87dbf279a0f64b57":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"16b3cb1fd77c4a96","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/16b3cb1fd77c4a96","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235468,"stop":1749741235468,"duration":0}},{"uid":"3d0039b514d90831","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/3d0039b514d90831","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828054,"stop":1749740828054,"duration":0}},{"uid":"54801ac502546318","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/54801ac502546318","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654723,"stop":1749740654723,"duration":0}}]},"473f217d34ce412a1c7c6ef88ce601b0":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"973ab7c4e7ea4607","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/973ab7c4e7ea4607","status":"passed","time":{"start":1749710087085,"stop":1749710087316,"duration":231}}]},"372ffdd854072b56832ab701bdd1d5af":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"7ff08e38a32ab08d","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/7ff08e38a32ab08d","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237616,"stop":1749741237616,"duration":0}},{"uid":"ec732b56fb5dd77f","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/ec732b56fb5dd77f","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740830314,"stop":1749740830314,"duration":0}},{"uid":"adaaae432cb41c40","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/adaaae432cb41c40","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656891,"stop":1749740656891,"duration":0}}]},"27293e23bcbc72f8dfdd8e15f433e77d":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"44f3de86e107c4bd","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/44f3de86e107c4bd","status":"passed","time":{"start":1749710066845,"stop":1749710067089,"duration":244}}]},"f1572bbf0f3b8a8e9a905bc5bcac4e94":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"c1c421bdaafcedf","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/c1c421bdaafcedf","status":"passed","time":{"start":1749710068589,"stop":1749710070157,"duration":1568}}]},"cf641291d2f41c5837764b92d7ec6e3a":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"8aff3664b8cb9783","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/8aff3664b8cb9783","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236046,"stop":1749741236046,"duration":0}},{"uid":"131db9950639a0b","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/131db9950639a0b","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828656,"stop":1749740828656,"duration":0}},{"uid":"c42966927ad95934","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/c42966927ad95934","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655291,"stop":1749740655291,"duration":0}}]},"b7dd4a1dd68ca430a777ed12f6dc0d2d":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"3c0dedaa45c6ac6a","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/3c0dedaa45c6ac6a","status":"passed","statusDetails":"XPASS Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)","time":{"start":1749710078004,"stop":1749710078239,"duration":235}}]},"61d0500454039e109d4eb633788ac564":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"462078657559fab","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/462078657559fab","status":"passed","time":{"start":1749710092393,"stop":1749710092545,"duration":152}}]},"059c39232a2f796454ac5b73f639c451":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"a403fee4198fd62a","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/a403fee4198fd62a","status":"passed","statusDetails":"XPASS Бэк принимает отрицательное значение","time":{"start":1749710076398,"stop":1749710076715,"duration":317}}]},"9fff5d7e371d4d67d88ccf3b6f872341":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"386fb2a6c5c1adc9","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/386fb2a6c5c1adc9","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233890,"stop":1749741233890,"duration":0}},{"uid":"d2c93becf3123359","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/d2c93becf3123359","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826395,"stop":1749740826395,"duration":0}},{"uid":"1ca22fa7615cf67","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/1ca22fa7615cf67","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653151,"stop":1749740653151,"duration":0}}]},"f4f441dfc4d434473f513942b14e4271":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"cd72978e3829b845","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/cd72978e3829b845","status":"passed","time":{"start":1749710087778,"stop":1749710087979,"duration":201}}]},"acc0a6247a23c83e0afd67b8e1f0ee00":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"596d0147330eb20f","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/596d0147330eb20f","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237902,"stop":1749741237902,"duration":0}},{"uid":"c5a45e11eadecddf","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/c5a45e11eadecddf","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740830616,"stop":1749740830616,"duration":0}},{"uid":"c69f19fe7e529a5c","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/c69f19fe7e529a5c","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740657178,"stop":1749740657178,"duration":0}}]},"9492acc96be930b3b32aac9faec248ad":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"8c98363a51ee3527","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/8c98363a51ee3527","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235909,"stop":1749741235909,"duration":0}},{"uid":"6975e157022bf87e","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/6975e157022bf87e","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828511,"stop":1749740828511,"duration":0}},{"uid":"ca9e396fc931ab43","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/ca9e396fc931ab43","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655153,"stop":1749740655153,"duration":0}}]},"c81de9655ab70008c4824393ab9b609e":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"b3064e9a4a02f2f0","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/b3064e9a4a02f2f0","status":"passed","time":{"start":1749710087318,"stop":1749710087581,"duration":263}}]},"23e3977369731db2f8f642c865586950":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"18200fbab7b20222","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/18200fbab7b20222","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234104,"stop":1749741234104,"duration":0}},{"uid":"68f7316695148bc5","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/68f7316695148bc5","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826623,"stop":1749740826623,"duration":0}},{"uid":"97da4753b51ca702","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/97da4753b51ca702","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653367,"stop":1749740653367,"duration":0}}]},"3768af2b099f4d1541df6790e6d51761":{"statistic":{"failed":0,"broken":0,"skipped":3,"passed":0,"unknown":0,"total":3},"items":[{"uid":"9ba6d4c2eb2a216f","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/9ba6d4c2eb2a216f","status":"skipped","statusDetails":"XFAIL Пограничное значение 0 требует уточнения требований\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234321,"stop":1749741234321,"duration":0}},{"uid":"eaa5a4753c476e86","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/eaa5a4753c476e86","status":"skipped","statusDetails":"XFAIL Пограничное значение 0 требует уточнения требований\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826851,"stop":1749740826851,"duration":0}},{"uid":"e0e4dc48902cd874","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/e0e4dc48902cd874","status":"skipped","statusDetails":"XFAIL Пограничное значение 0 требует уточнения требований\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653586,"stop":1749740653586,"duration":0}}]},"c3ad3c75eee25d975e506d0c0ceefa84":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"8d0c9dd2590e37e7","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/8d0c9dd2590e37e7","status":"passed","time":{"start":1749710065108,"stop":1749710065413,"duration":305}}]},"250b3b212279573f5e632f0f4450828a":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"64bc68e2c419ebdb","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/64bc68e2c419ebdb","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233543,"stop":1749741233543,"duration":0}},{"uid":"37f6c26cc8b917bd","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/37f6c26cc8b917bd","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826018,"stop":1749740826018,"duration":0}},{"uid":"ff82e9db4a2b57ee","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/ff82e9db4a2b57ee","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740652789,"stop":1749740652789,"duration":0}}]},"ea846c4fba96e0d1d9d09786d07f5221":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"5f668c6fb75c811","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/5f668c6fb75c811","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233410,"stop":1749741233410,"duration":0}},{"uid":"b3fa027dda3177eb","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/b3fa027dda3177eb","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740825875,"stop":1749740825875,"duration":0}},{"uid":"31db1a51828bc0a6","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/31db1a51828bc0a6","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740652653,"stop":1749740652653,"duration":0}}]},"8224906e80748855ee2ae973ed2a412d":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"e499a495825420b6","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/e499a495825420b6","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234173,"stop":1749741234173,"duration":0}},{"uid":"f51a1ddea584fdec","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/f51a1ddea584fdec","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826694,"stop":1749740826694,"duration":0}},{"uid":"53c92d53627baf08","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/53c92d53627baf08","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653435,"stop":1749740653435,"duration":0}}]},"47ad661dee74c74b77802293d2485ec8":{"statistic":{"failed":0,"broken":0,"skipped":3,"passed":0,"unknown":0,"total":3},"items":[{"uid":"244281bcb2f0675a","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/244281bcb2f0675a","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234757,"stop":1749741234757,"duration":0}},{"uid":"18e037a1f8675b1d","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/18e037a1f8675b1d","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827308,"stop":1749740827308,"duration":0}},{"uid":"8f153c12aab129d5","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/8f153c12aab129d5","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654022,"stop":1749740654022,"duration":0}}]},"96f74604c2170a1f91a88a047bacd430":{"statistic":{"failed":0,"broken":0,"skipped":3,"passed":0,"unknown":0,"total":3},"items":[{"uid":"7a25effe5b57e396","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/7a25effe5b57e396","status":"skipped","statusDetails":"XFAIL Бэк принимает отрицательное значение\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234253,"stop":1749741234253,"duration":0}},{"uid":"7c7a1e0f31e4c270","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/7c7a1e0f31e4c270","status":"skipped","statusDetails":"XFAIL Бэк принимает отрицательное значение\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826778,"stop":1749740826778,"duration":0}},{"uid":"902e29acc174ec25","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/902e29acc174ec25","status":"skipped","statusDetails":"XFAIL Бэк принимает отрицательное значение\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653517,"stop":1749740653517,"duration":0}}]},"36b2769c56e8e241e751daddb2086ff7":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"428a0eee48c34147","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/428a0eee48c34147","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741238120,"stop":1749741238120,"duration":0}},{"uid":"7b680577fd4b2aac","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/7b680577fd4b2aac","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740830844,"stop":1749740830844,"duration":0}},{"uid":"11cf3be5ddd9750e","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/11cf3be5ddd9750e","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740657399,"stop":1749740657399,"duration":0}}]},"432af4f08a7d5d740d251eb98411848b":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"9fccccefa73b698b","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/9fccccefa73b698b","status":"passed","time":{"start":1749710071134,"stop":1749710071532,"duration":398}}]},"5e4e3f3fdabf9d808a294b296cde1716":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"c2c3b742552ead45","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/c2c3b742552ead45","status":"passed","time":{"start":1749710088176,"stop":1749710088368,"duration":192}}]},"765198acce685b197c7e10d319459906":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"8860f9c2077a7ff1","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/8860f9c2077a7ff1","status":"passed","time":{"start":1749710066063,"stop":1749710066527,"duration":464}}]},"82caea6867a69708f62244f113e9e77f":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"c16efb51ba7be7d7","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/c16efb51ba7be7d7","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235330,"stop":1749741235330,"duration":0}},{"uid":"811bdbc665af33b","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/811bdbc665af33b","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827910,"stop":1749740827910,"duration":0}},{"uid":"41a6bad377230761","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/41a6bad377230761","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654587,"stop":1749740654587,"duration":0}}]},"d2d6b127421e881191e1b41c382cd2a9":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"a10501ad469f3ca5","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/a10501ad469f3ca5","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237397,"stop":1749741237397,"duration":0}},{"uid":"4152b233b15d1fcb","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/4152b233b15d1fcb","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740830084,"stop":1749740830084,"duration":0}},{"uid":"a0bbdea8f28a7caa","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/a0bbdea8f28a7caa","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656674,"stop":1749740656674,"duration":0}}]},"1f4e1df2037d6c6194e1233b5d3f247c":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"ed2c2db0c647cff0","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/ed2c2db0c647cff0","status":"passed","time":{"start":1749710090145,"stop":1749710090403,"duration":258}}]},"22837b095a0e2dbbbfac0c68950d0134":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"31aefcb102bca369","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/31aefcb102bca369","status":"passed","time":{"start":1749710091456,"stop":1749710092073,"duration":617}}]},"ec63fe8713670e034406e6e7449bdf70":{"statistic":{"failed":0,"broken":0,"skipped":3,"passed":0,"unknown":0,"total":3},"items":[{"uid":"b544a1c4b5e6a303","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/b544a1c4b5e6a303","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741234672,"stop":1749741234672,"duration":0}},{"uid":"2c031751a922b66e","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/2c031751a922b66e","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827224,"stop":1749740827224,"duration":0}},{"uid":"fafcf21ad076dfff","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/fafcf21ad076dfff","status":"skipped","statusDetails":"XFAIL Известный баг: длинный заголовок custom field без пробелов не влезает в тултип (APP-2763)\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740653937,"stop":1749740653937,"duration":0}}]},"824fc9cc8ab186ce171823c2d8a932e0":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"81db2862edae56e7","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/81db2862edae56e7","status":"passed","time":{"start":1749710088631,"stop":1749710089408,"duration":777}}]},"56babd9437352148d8ae9754a3d67681":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"522c175424d80674","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/522c175424d80674","status":"passed","time":{"start":1749710079721,"stop":1749710079952,"duration":231}}]},"4ab1fa53fbdb3058777b53a214a4b162":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"af3e9c4e09b8801c","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/af3e9c4e09b8801c","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233689,"stop":1749741233689,"duration":0}},{"uid":"c506451a4784e984","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/c506451a4784e984","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826180,"stop":1749740826180,"duration":0}},{"uid":"8286eba0158581de","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/8286eba0158581de","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740652941,"stop":1749740652941,"duration":0}}]},"7d5bf5b15ba588b121dc75ba08f01ecb":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"e64c3130560db306","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/e64c3130560db306","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236196,"stop":1749741236196,"duration":0}},{"uid":"dae66fdc467c5c56","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/dae66fdc467c5c56","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828811,"stop":1749740828811,"duration":0}},{"uid":"4afe4e20f18a5092","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/4afe4e20f18a5092","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655458,"stop":1749740655458,"duration":0}}]},"5c3f0ef95bb7c39f2876215f599c054c":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"5a9afe23aa2e0a5e","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/5a9afe23aa2e0a5e","status":"passed","time":{"start":1749710087980,"stop":1749710088175,"duration":195}}]},"06d5559547826a07c1b0bd3144457ac2":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"d50b54ead663973c","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/d50b54ead663973c","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236614,"stop":1749741236614,"duration":0}},{"uid":"5677e412d7d14f02","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/5677e412d7d14f02","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829254,"stop":1749740829254,"duration":0}},{"uid":"96a9d478a9e1f311","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/96a9d478a9e1f311","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655878,"stop":1749740655878,"duration":0}}]},"e42ce7bc007087659574c087d50cc160":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"af41dd2ecd45f8b3","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/af41dd2ecd45f8b3","status":"passed","time":{"start":1749710092546,"stop":1749710095662,"duration":3116}}]},"39b670d8fc35f10e0590532ae0411b51":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"14e4cc125ca23a63","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/14e4cc125ca23a63","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741097945,"stop":1749741097945,"duration":0}},{"uid":"11e3723cf5ce2af4","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/11e3723cf5ce2af4","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740692501,"stop":1749740692501,"duration":0}},{"uid":"91c5dbe566370c0","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/91c5dbe566370c0","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740515963,"stop":1749740515963,"duration":0}}]},"0ed5e545d8c0f89bd81250283d88d1f1":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"29ee04e0e3f2125c","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/29ee04e0e3f2125c","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233476,"stop":1749741233476,"duration":0}},{"uid":"b6c7dc4f6e84a0e1","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/b6c7dc4f6e84a0e1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740825946,"stop":1749740825946,"duration":0}},{"uid":"9450d640bb230b0","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/9450d640bb230b0","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740652720,"stop":1749740652720,"duration":0}}]},"5073e64d368099b9977d7f384d36fa1e":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"5eabb56f2fe74659","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/5eabb56f2fe74659","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237834,"stop":1749741237834,"duration":0}},{"uid":"ca052b8051040abf","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/ca052b8051040abf","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740830543,"stop":1749740830543,"duration":0}},{"uid":"2e08b1359523e25e","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/2e08b1359523e25e","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740657110,"stop":1749740657110,"duration":0}}]},"94235c8714f9c27ff625dcad997f2a85":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"b4c4c83faf93ecb1","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/b4c4c83faf93ecb1","status":"passed","time":{"start":1749710081629,"stop":1749710082278,"duration":649}}]},"c627bc339bebe7451f302489dcbe3ac7":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"d0604fa0b086f76b","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/d0604fa0b086f76b","status":"passed","time":{"start":1749710081344,"stop":1749710081627,"duration":283}}]},"8adadf90c9d53664db97ee9093b83ddf":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"25c36c36531f8bbf","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/25c36c36531f8bbf","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741236546,"stop":1749741236546,"duration":0}},{"uid":"75bd01da333dc918","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/75bd01da333dc918","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829182,"stop":1749740829182,"duration":0}},{"uid":"c46d8da2e8eaad51","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/c46d8da2e8eaad51","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740655812,"stop":1749740655812,"duration":0}}]},"95878e592727284373a05e8ba3acc67c":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"a7773c6da72fb395","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/a7773c6da72fb395","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237970,"stop":1749741237970,"duration":0}},{"uid":"cba304d415965fdf","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/cba304d415965fdf","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740830687,"stop":1749740830687,"duration":0}},{"uid":"2d78488753ac0d3a","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/2d78488753ac0d3a","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740657245,"stop":1749740657245,"duration":0}}]},"2b1c8a41ae9b94d897f68b7f410d75b0":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"9c20e6c779b32015","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/9c20e6c779b32015","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235536,"stop":1749741235536,"duration":0}},{"uid":"6f5a171a399fe65","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/6f5a171a399fe65","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740828126,"stop":1749740828126,"duration":0}},{"uid":"38262f66c5ea0c68","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/38262f66c5ea0c68","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654789,"stop":1749740654789,"duration":0}}]},"0b56ac40efa740c965cd250745060946":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"7a2f27677e31c623","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/7a2f27677e31c623","status":"passed","time":{"start":1749710076981,"stop":1749710077243,"duration":262}}]},"9d931d5b05e1b4538f8469bc0436fe63":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"e67473921f0c1228","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/e67473921f0c1228","status":"passed","time":{"start":1749710084928,"stop":1749710085458,"duration":530}}]},"105eaabb0b4acabca0761ead0a406c3e":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"e25328dc354cb707","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/e25328dc354cb707","status":"passed","time":{"start":1749710082280,"stop":1749710082806,"duration":526}}]},"34b25a0b7a3903005ca233e41a171121":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"8923369dc92f1385","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/8923369dc92f1385","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741235246,"stop":1749741235246,"duration":0}},{"uid":"cba443fa721948b2","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/cba443fa721948b2","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740827825,"stop":1749740827825,"duration":0}},{"uid":"8c0e8e345754d9e1","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/8c0e8e345754d9e1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740654505,"stop":1749740654505,"duration":0}}]},"8b6030539fc7cb8d3ef9c5c122bde0bf":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"fd36553313639f01","reportUrl":"https://vaizcom.github.io/autotests/113//#testresult/fd36553313639f01","status":"passed","time":{"start":1749710075847,"stop":1749710076130,"duration":283}}]}}