{"uid":"76477024894e3d51","name":"Валидация: создание борды с именем — ожидаемый статус 200","fullName":"tests.test_backend.board.board_validation_test#test_create_board_name_validation","historyId":"250b3b212279573f5e632f0f4450828a","time":{"start":1749798748088,"stop":1749798748329,"duration":241},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":true,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"delete_output_dir","time":{"start":1749798742635,"stop":1749798742635,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"owner_client","time":{"start":1749798742635,"stop":1749798743126,"duration":491},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"base_url","time":{"start":1749798742635,"stop":1749798742635,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"pytestconfig","time":{"start":1749798742635,"stop":1749798742635,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"_verify_url","time":{"start":1749798742635,"stop":1749798742635,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"temp_space","time":{"start":1749798743126,"stop":1749798744123,"duration":997},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"temp_project","time":{"start":1749798744123,"stop":1749798745984,"duration":1861},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"passed","steps":[{"name":"Проверка, что API вернул статус 200 при exactly 50 chars","time":{"start":1749798748329,"stop":1749798748329,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"attachments":[{"uid":"4781367f0efca2e3","name":"stdout","source":"4781367f0efca2e3.txt","type":"text/plain","size":83}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":1,"hasContent":true},"afterStages":[{"name":"temp_space::0","time":{"start":1749798778176,"stop":1749798778980,"duration":804},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"backend"},{"name":"parentSuite","value":"tests.test_backend.board"},{"name":"suite","value":"board_validation_test"},{"name":"host","value":"pkrvmxyh4eaekms"},{"name":"thread","value":"2537-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_backend.board.board_validation_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"expected_status","value":"200"},{"name":"name","value":"'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":8,"skipped":0,"passed":6,"unknown":0,"total":14},"items":[{"uid":"e9b03a8c7ab64d20","reportUrl":"https://vaizcom.github.io/autotests/128//#testresult/e9b03a8c7ab64d20","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f254b41e350>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749798175160,"stop":1749798175160,"duration":0}},{"uid":"cf5ff85e189625c9","reportUrl":"https://vaizcom.github.io/autotests/127//#testresult/cf5ff85e189625c9","status":"passed","time":{"start":1749797896847,"stop":1749797897188,"duration":341}},{"uid":"831af5c3e597e0c8","reportUrl":"https://vaizcom.github.io/autotests/126//#testresult/831af5c3e597e0c8","status":"passed","time":{"start":1749745006705,"stop":1749745006945,"duration":240}},{"uid":"153d411d72e519b5","reportUrl":"https://vaizcom.github.io/autotests/125//#testresult/153d411d72e519b5","status":"passed","time":{"start":1749744404565,"stop":1749744404876,"duration":311}},{"uid":"b3389e93346a349c","reportUrl":"https://vaizcom.github.io/autotests/124//#testresult/b3389e93346a349c","status":"passed","time":{"start":1749744318786,"stop":1749744319075,"duration":289}},{"uid":"67b0ac727647ddaa","reportUrl":"https://vaizcom.github.io/autotests/123//#testresult/67b0ac727647ddaa","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6ed7455e50>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749744002803,"stop":1749744002803,"duration":0}},{"uid":"cb37b0aadfe72844","reportUrl":"https://vaizcom.github.io/autotests/122//#testresult/cb37b0aadfe72844","status":"passed","time":{"start":1749743623161,"stop":1749743623405,"duration":244}},{"uid":"3df0292d06b993ad","reportUrl":"https://vaizcom.github.io/autotests/119//#testresult/3df0292d06b993ad","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc7b5913490>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742819949,"stop":1749742819949,"duration":0}},{"uid":"be47c0907a298a1e","reportUrl":"https://vaizcom.github.io/autotests/118//#testresult/be47c0907a298a1e","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9cb88f1f10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742667325,"stop":1749742667325,"duration":0}},{"uid":"a9e0928eec6a4278","reportUrl":"https://vaizcom.github.io/autotests/117//#testresult/a9e0928eec6a4278","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2b9f21f250>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742497080,"stop":1749742497080,"duration":0}},{"uid":"64bc68e2c419ebdb","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/64bc68e2c419ebdb","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233543,"stop":1749741233543,"duration":0}},{"uid":"37f6c26cc8b917bd","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/37f6c26cc8b917bd","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740826018,"stop":1749740826018,"duration":0}},{"uid":"ff82e9db4a2b57ee","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/ff82e9db4a2b57ee","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740652789,"stop":1749740652789,"duration":0}}]},"tags":["backend"]},"source":"76477024894e3d51.json","parameterValues":["200","'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'"]}